export { default as SignUp } from './SignUp'
export { default as SignIn } from './SignIn'
export { default as ForgotPassword1 } from './ForgotPassword1'
export { default as ForgotPassword2 } from './ForgotPassword2'
export { default as ChangePassword } from './ChangePassword'
export { default as Dashboard } from './Dashboard'